### ISSUE TITLE
Open API Spec + Swagger

### ISSUE THREAD

**Issue by hay-kot** [levinologylabs/gottl#4]
## Description

Documentation for endpoints should be automatically generated via 

- https://github.com/swaggo/swag

## Tasks

- [ ] Comment Existing Endpoints
- [ ] Taskfile Script
- [ ] Determine if we want to embed swagger UI
- [ ] Serve Swagger JSON from API
