### ISSUE TITLE
Centralized Error Handling

### ISSUE THREAD

**Issue by hay-kot** [levinologylabs/gottl#5]
## Description

Use an adapter pattern for handling errors through the Rest API

## Tasks

- [ ] Error middleware for adapting handlers
- [ ] Generic/structured error message (JSON format)
  - [ ] Ensure this supports validation of fields and proper feedback
